### ISSUE TITLE
Writing in Markdown mode

### ISSUE THREAD

**Issue by josephernest** [ether/ep_markdown#21] opened 2016-11-30 20:39 UTC
I tried this:

1. Enable "Show Markdown"

2. Write text in Markdown syntax, for example `**hello** this is markdown`

3. Disable "Show Markdown"

Then the `**hello**` text, that was written during "markdown mode on", is not interpreted as **hello** (in bold). Why? Is this normal behaviour?

Demo: https://annuel.framapad.org/p/dCfecDEfqw

**Comment by pichouk** [comment] 2017-06-23 09:39
I guess it duplicates #4

**Comment by JohnMcLear** [comment] 2020-03-15 21:06
I didn't implement this intentionally..  Do people really want this?  It seems like a terrible idea?

**Comment by JohnMcLear** [comment] 2020-03-15 21:09
Defo a duplicate of #4

**Closed by JohnMcLear** 2020-03-15 21:09 UTC
